### ISSUE TITLE
without conflict, the version of brave-opentracing I depend on was cast as 0.31.1

### ISSUE THREAD

**Issue by broucetrong** [openzipkin-contrib/brave-opentracing#100]
my jar names call-chain-trace-api depends on brave-opentracing with version 0.34.0
![image](https://user-images.githubusercontent.com/20812756/75106381-e0fbdc80-5656-11ea-86f2-e756e3b12d79.png)

Then, my another project depended on my jar call-chain-trace-api, but the version of brave-opentracing was cast as 0.31.1
![image](https://user-images.githubusercontent.com/20812756/75106358-b3169800-5656-11ea-8789-ea5171c1e07c.png)

In addition, do not exists conflict. Before I depended on my jar call-chain-trace-api, the project never depended on brave-opentracing

This question has been bothering me for a long time, if anybody knows the reason, please tell me, thanks very much !

**Comment by adriancole** [comment]
this is more a question about sleuth. the sleuth dependency is setting the opentracing version because in 2.0 of sleuth it is using opentracing 0.31, which is incompatible with opentracing 0.33 in brave-opentracing latest. If you upgrade to latest boot/sleuth, you should be ok. Also, if you exclude io.zipkin.brave:* when importing your project, you should be ok.

For more questions, please hop on gitter https://gitter.im/spring-cloud/spring-cloud-sleuth
