### ISSUE TITLE
Log and Tag are not utilized

### ISSUE THREAD

**Issue by zmzheng** [openzipkin-contrib/brave-opentracing#6]
Opentracing and Brave have different designs for logging events. Opentracing uses logs and tags while Brave uses annotations. Currently, brave-opentracing hasn't converted logs, tags and baggageItems to annotations in Brave, thus the information traced using log(), setTag() is not sent to Zipkin.

**Comment by michaelsembwever** [comment]
Anyone keen to submit a PR for this?

**Comment by adriancole** [comment]
this has all the code involved https://github.com/openzipkin/brave/tree/master/brave/src/test/java/brave/features/opentracing

**Comment by adriancole** [comment]
Brave can help with baggage, using ExtraFieldsPropagation. However, it currently only supports single-shot mutation (up-front, not adding keys in the middle of a span).

Otherwise, the concerns mentioned in this issue are addressed one way or another since it was opened. Feel free to open an issue about baggage
