### ISSUE TITLE
IllegalArgumentException on BraveScopeManager.active().close()

### ISSUE THREAD

**Issue by hanson76** [openzipkin-contrib/brave-opentracing#73]
The IllegalArgumentException that is being thrown in Scope#close() in ScopeManager#active() 
is troublesome.
There are places where you either want to reuse an already active span, or create a new span if none exists. The opentracing API for Scope#close() does mention that it should end the active period of the thread and scope. I suggest that Scope#close() should be a no-op if the Scope is returned from ScopeManager#active() instead of throwing an exception.

An examples of this usage is the spring-web interfecptor in opentracing-contrib/java-spring-web [1] 

[1] https://github.com/opentracing-contrib/java-spring-web/blob/master/opentracing-spring-web/src/main/java/io/opentracing/contrib/spring/web/interceptor/TracingHandlerInterceptor.java

**Comment by adriancole** [comment]
Fixed by #74

PS I would not recommend using that instrumentation by the way, especially if you are using brave. The whole point of a bridge is that you can mix and match better things. There's no good reason to use ot-contrib for things like spring when brave's instrumentation is far more used and still lets you use OT apis for things that brave doesn't have.
