### ISSUE TITLE
Fix opentracing 0.32.0

### ISSUE THREAD

**Issue by tanumats** [openzipkin-contrib/brave-opentracing#91]
Version 0.32.0 of opentracing has been released.
Please reflect.
https://github.com/opentracing/opentracing-java/releases/tag/release-0.32.0-RC1

Changes
https://github.com/opentracing/opentracing-java/issues/314

**Comment by adriancole** [comment]
this is now released.. there are some problems to deal with as I just now looked at this cc @felixbarny @tylerbenson


for example, OT has no sampling api (still) and we are supposed to interpret `Tags.SAMPLING_PRIORITY` as a sampling hint. We also play games with the kind tag to figure out if we should share a span ID or not.

this is an issue with the new deferred `io.opentracing.tag.Tag` api. There's no docs on that type, but presume any tags could be done. However, the signature of the type includes Span, not SpanBuilder. This creates an ordering concern for things that we'd prefer to do up front, for example, deal with sampling.

One way is to make a dummy span implementation that catches the result of `Tag.set` so that we can inspect the value as if it were made with SpanBuilder directly. Another is for OT to evaluate this api and if it is appropriate to add to span builder, or if sampling can't be added as a real api as that's the bigger problem.

**Comment by adriancole** [comment]
significantly revised the text of the above comment

**Comment by adriancole** [comment]
PS I'm not sure I agree with the design here, but if one were to try to fix the api you could overload `set` with a `SpanBuilder` param.

That way, there's no race and it has parity between the two call sites that are eventually invoked (Span.setTag, SpanBuilder.withTag)

**Comment by tylerbenson** [comment]
@adriancole I'm a bit confused... what changed in 0.32.0 that is raising this concern?  As far as I can tell, the API's you mentioned have been in place for a long time.

**Comment by adriancole** [comment]
long time and in 0.31 are different questions. if you change from 0.31 to
0.32 you now have to implement a new method on span and span builder which
accepts tag and value.

**Comment by adriancole** [comment]
@tylerbenson more literally below:

```java
  @Override public <T> BraveSpanBuilder withTag(Tag<T> tag, T value) {
    // Assuming Tag implementations are only allowed to call span.setTag with the given key once?
    // We could make a dummy span captor impl to catch the value as we have a builder, not span here.
    // The tag could be a pseudo-api (ex sampling priority) desirable prior to building a span.
    // 
    //  public interface Tag<T> {
    //    String getKey();
    //    void set(Span span, T value);
    //  }
    return this;
  }
```

**Comment by adriancole** [comment]
I will later raise a pull request to show the impact of this design

**Comment by adriancole** [comment]
added an issue about the tag builder api https://github.com/opentracing/opentracing-java/issues/340

**Comment by adriancole** [comment]
added this about things still missing from span context https://github.com/opentracing/opentracing-java/issues/341

**Comment by adriancole** [comment]
note: 0.32 doesn't remove any deprecated code, so that means 0.33 will be a pro and a con. pro is code deleted, con is api break again https://github.com/opentracing/opentracing-java/issues/338

**Comment by hochraldo** [comment]
Any news on this? opentracing 0.33 is already out. Any plans to support this in the near future?

**Comment by adriancole** [comment]
yeah sorry weekend got away from me. will take a look tomorrow. main thing
is to add invoker tests to prove the version range works.

**Comment by adriancole** [comment]
https://github.com/openzipkin-contrib/brave-opentracing/releases/tag/0.34.0
